### ISSUE TITLE
Cluster.py: Problems reading array data

### ISSUE THREAD

**Issue by s-gordon** [msmbuilder/msmbuilder-legacy#217]
Hi all,

After completing the MSMBUILDER2 tutorials, I tried to apply the same steps involved to my own data set of trajectories. After converting these frames to XTC (I was having issues with the DCD reader) using a combination of catdcd and Gromac's trjconv tools, I converted my trajectories into .lh5 files using the ConvertDataToHDF.py script, which appeared to complete normally.

Next, I tried to cluster the data set using the command:

```
python2.7 ../scripts/Cluster.py rmsd hybrid -d 0.045 -l 50
...which worked for the Tutorial data set previously. This spits out the following error log:

--------------------------------------------------------------------------------

MSMBuilder version 2.6.0.dev-Unknown

See file AUTHORS for a list of MSMBuilder contributors.

--------------------------------------------------------------------------------

Copyright 2011 Stanford University.

MSMBuilder comes with ABSOLUTELY NO WARRANTY.

MSMBuilder is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

--------------------------------------------------------------------------------

Please cite the following references:

GR Bowman, X Huang, and VS Pande. Methods 2009. Using generalized ensemble 
simulations and Markov state models to identify conformational states.

KA Beauchamp, GR Bowman, TJ Lane, L Maibaum, IS Haque, VS Pande.  JCTC 2011.
MSMBuilder2: Modeling Conformational Dynamics
at the Picosecond to Millisecond Timescale

IS Haque, KA Beauchamp, VS Pande.  In preparation.
A Fast 3 x N Matrix Multiply Routine for Calculation of Protein RMSD.

--------------------------------------------------------------------------------
{'alg': 'hybrid',
 'hybrid_distance_cutoff': 0.045,
 'hybrid_global_iters': 0,
 'hybrid_ignore_max_objective': False,
 'hybrid_local_num_iters': 50,
 'hybrid_num_clusters': None,
 'hybrid_too_close_cutoff': 0.0001,
 'metric': 'rmsd',
 'output_dir': 'Data/',
 'project': 'ProjectInfo.yaml',
 'quiet': False,
 'rmsd_atom_indices': 'AtomIndices.dat',
 'stride': 1}
11:39:03 - RMSD metric - loading only the atom indices required
HDF5-DIAG: Error detected in HDF5 (1.8.4-patch1) thread 139968538093312:
  #000: ../../../src/H5Dio.c line 153 in H5Dread(): selection+offset not within extent
    major: Dataspace
    minor: Out of range
Traceback (most recent call last):
  File "../scripts/Cluster.py", line 228, in <module>
    main(args, metric)
  File "../scripts/Cluster.py", line 203, in main
    trajs = load_trajectories(args.project, args.stride, atom_indices)
  File "../scripts/Cluster.py", line 121, in load_trajectories
    traj = project.load_traj(i, stride=stride, atom_indices=atom_indices)
  File "/usr/local/lib/python2.7/dist-packages/msmbuilder-2.6.0-py2.7-linux-x86_64.egg/msmbuilder/project/project.py", line 340, in load_traj
    AtomIndices=atom_indices)
  File "/usr/local/lib/python2.7/dist-packages/msmbuilder-2.6.0-py2.7-linux-x86_64.egg/msmbuilder/Trajectory.py", line 722, in load_trajectory_file
    return Trajectory.load_from_lhdf(Filename, JustInspect=JustInspect, Stride=Stride, AtomIndices=AtomIndices)
  File "/usr/local/lib/python2.7/dist-packages/msmbuilder-2.6.0-py2.7-linux-x86_64.egg/msmbuilder/Trajectory.py", line 627, in load_from_lhdf
    A = cls.load_from_hdf(TrajFilename, Stride=Stride, AtomIndices=AtomIndices)
  File "/usr/local/lib/python2.7/dist-packages/msmbuilder-2.6.0-py2.7-linux-x86_64.egg/msmbuilder/Trajectory.py", line 596, in load_from_hdf
    chunk_list = list(cls.enum_chunks_from_hdf(TrajFilename, Stride=Stride, AtomIndices=AtomIndices, ChunkSize=ChunkSize))
  File "/usr/local/lib/python2.7/dist-packages/msmbuilder-2.6.0-py2.7-linux-x86_64.egg/msmbuilder/Trajectory.py", line 507, in enum_chunks_from_hdf
    A['AtomID'] = np.array(F.root.AtomID[AtomIndices], dtype=np.int32)
  File "/usr/lib/python2.7/dist-packages/tables/array.py", line 689, in __getitem__
    arr = self._readCoords(coords)
  File "/usr/lib/python2.7/dist-packages/tables/array.py", line 792, in _readCoords
    self._g_readCoords(coords, nparr)
  File "hdf5Extension.pyx", line 1134, in tables.hdf5Extension.Array._g_readCoords (tables/hdf5Extension.c:9869)
tables.exceptions.HDF5ExtError: Problems reading the array data.
Closing remaining open files: /home/<user>/Downloads/msmbuilder-2.6.0_3/Tutorial/Trajectories/trj0.lh5... done
```

At the conclusion of this, no files are created in the ./Data directory.

I've farmed through the relevant scripts to try and diagnose what the issue might be, but nothing screams out. 

The trajectories involve only a small molecule (9 atoms), and the total data set is equivalent to roughly 50 Mb.

I'd greatly appreciate it if anyone can help me figure out what the issue might be.

Cheers.

**Comment by aasthajhunjhunwala** [comment]
Hi all, I've been facing issues trying to use .h5 file datasets. I keep getting this error for the code 
ds = dataset('traj-0000.h5')
len(ds)

/anaconda3/envs/MDS/lib/python2.7/site-packages/tables/group.pyc in _g_check_has_child(self, name)
    396             raise NoSuchNodeError(
    397                 "group ``%s`` does not have a child named ``%s``"
--> 398                 % (self._v_pathname, name))
    399         return node_type
    400 

NoSuchNodeError: group ``/`` does not have a child named ``/arr_0``

Even though the h5 file is in the same directory as the Jupyter notebook. Any help/fixes will be highly appreciated.

**Comment by aasthajhunjhunwala** [comment]
I think MSMBuilder doesn't account for the latest Pytables update. Here's a link to a Pytables [Similar issue] (https://github.com/PV-Lab/bayesim/issues/1)
