### ISSUE TITLE
AttributeError: type object 'RMSD' has no attribute 'TheoData'

### ISSUE THREAD

**Issue by cxhernandez** [msmbuilder/msmbuilder-legacy#411]
Trying to use lprmsd with Assign.

Traceback:

```
Traceback (most recent call last):
  File "/home/cxh/anaconda/bin/Assign", line 9, in <module>
    load_entry_point('msmbuilder==2.8.3', 'console_scripts', 'Assign')()
  File "/home/cxh/anaconda/lib/python2.7/site-packages/msmbuilder/scripts/Assign.py", line 99, in entry_point
    main(args, metric)
  File "/home/cxh/anaconda/lib/python2.7/site-packages/msmbuilder/scripts/Assign.py", line 93, in main
    distances_path)
  File "/home/cxh/anaconda/lib/python2.7/site-packages/msmbuilder/assigning.py", line 166, in assign_with_checkpoint
    pgens = metric.prepare_trajectory(generators)
  File "/home/cxh/anaconda/lib/python2.7/site-packages/msmbuilder.metrics.lprmsd-1.2-py2.7-linux-x86_64.egg/lprmsd.py", line 246, in prepare_trajectory
    T1 = LPTraj(trajectory, self.atomindices, self.permuteindices)
  File "/home/cxh/anaconda/lib/python2.7/site-packages/msmbuilder.metrics.lprmsd-1.2-py2.7-linux-x86_64.egg/lprmsd.py", line 74, in __init__
    self.TD = RMSD.TheoData(S.xyz[:, np.array(aidx)])
AttributeError: type object 'RMSD' has no attribute 'TheoData'
```

**Comment by autodataming** [comment]
how to solve the problem?

**Comment by cxhernandez** [comment]
I don't remember if this was ever fixed in the legacy version of MSMBuilder. I would recommend trying this with the latest edition at http://www.github.com/msmbuilder/msmbuilder
