### ISSUE TITLE
Problem with ConvertDataToHDF.py

### ISSUE THREAD

**Issue by nettieboden** [msmbuilder/msmbuilder-legacy#456]
I recently downloaded msmbuilder and was able to successfully walk through the tutorial. I am now trying to input some of my own data, which is in a dcd format. After seeing that other's had had problems in the past with dcd files, I converted it to xtc with mdtraj. Unfortunately, I am still getting the same error. Below is the error when I input the dcd file. The exact same error occurs when I use the xtc file. Any help would be greatly appreciated.

$ ConvertDataToHDF.py -s 4c4cnowat.pdb -S file_dcd -i traj
--------------------------------------------------------------------------------

MSMBuilder version 2.7.dev.dev-Unknown

See file AUTHORS for a list of MSMBuilder contributors.

--------------------------------------------------------------------------------

Copyright 2011 Stanford University.

MSMBuilder comes with ABSOLUTELY NO WARRANTY.

MSMBuilder is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

--------------------------------------------------------------------------------

Please cite the following references:

GR Bowman, X Huang, and VS Pande. Methods 2009. Using generalized ensemble 
simulations and Markov state models to identify conformational states.

KA Beauchamp, GR Bowman, TJ Lane, L Maibaum, IS Haque, VS Pande.  JCTC 2011.
MSMBuilder2: Modeling Conformational Dynamics
at the Picosecond to Millisecond Timescale

IS Haque, KA Beauchamp, VS Pande.  In preparation.
A Fast 3 x N Matrix Multiply Routine for Calculation of Protein RMSD.

--------------------------------------------------------------------------------
{'input_dir': 'traj',
 'min_length': 0,
 'pdb': '4c4cnowat.pdb',
 'project': 'ProjectInfo.yaml',
 'quiet': False,
 'rmsd_cutoff': -1,
 'source': 'file_dcd',
 'stride': 1}
14:14:49 - WARNING: Sorting trajectory files by numerical values in their names.
14:14:49 - Ensure that numbering is as intended.
14:14:49 - Found 1 traj dirs
Traceback (most recent call last):
  File "/Users/annetteboden/Library/Enthought/Canopy_64bit/User/bin/ConvertDataToHDF.py", line 5, in <module>
    pkg_resources.run_script('msmbuilder==2.7.dev', 'ConvertDataToHDF.py')
  File "/Users/annetteboden/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/pkg_resources.py", line 507, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/Users/annetteboden/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/pkg_resources.py", line 1272, in run_script
    execfile(script_filename, namespace, namespace)
  File "/Users/annetteboden/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/msmbuilder-2.7.dev-py2.7-macosx-10.6-x86_64.egg/EGG-INFO/scripts/ConvertDataToHDF.py", line 150, in <module>
    args.min_length, args.stride, rmsd_cutoff)
  File "/Users/annetteboden/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/msmbuilder-2.7.dev-py2.7-macosx-10.6-x86_64.egg/EGG-INFO/scripts/ConvertDataToHDF.py", line 81, in run
    pb.get_project().save(projectfn)
  File "/Users/annetteboden/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/msmbuilder-2.7.dev-py2.7-macosx-10.6-x86_64.egg/msmbuilder/project/builder.py", line 166, in get_project
    self.convert()
  File "/Users/annetteboden/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/msmbuilder-2.7.dev-py2.7-macosx-10.6-x86_64.egg/msmbuilder/project/builder.py", line 330, in convert
    raise RuntimeError('No conversion jobs found!')
RuntimeError: No conversion jobs found!

**Comment by kyleabeauchamp** [comment]
Your data has the wrong folder structure,  you might need another level of
folder.

**Comment by nettieboden** [comment]
You're magnificent. Thank you for your help and taking pity on a noob :)
